version: '3.8'

services:
  api:
    image: geralexsanguti/crm:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=CRMSarritelDb;Username=postgres;Password=A*mma+t2026/*-
      - Jwt__Key=OwrVqv5gN90gmIx5zrwbOLxPYgqazdZNFVTdoxwhFEZQnNp2u0sjCDeA4uUWNB0O
      - Jwt__Issuer=CRMSarritel
      - Jwt__Audience=CRMSarritelAudience
      - Jwt__ExpirationHours=24
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: geralexsanguti/crm-frontend:latest
    depends_on:
      - api
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=A*mma+t2026/*
      - POSTGRES_DB=CRMSarritelDb
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  postgres-data:
  grafana-data: